@startuml LiquorChart
skinparam Dpi 200
map 成品{
    80 => 一口柠檬
    81 =>威士忌
    82 =>女巫汤
    83 =>马天尼
    84 =>火辣荒地
    85 =>机场咖啡厅
    86 =>沙漠烈日
    87 =>纯粹欲望
    88 =>苦奎宁
    89 =>迷醉滋味
    90 =>海风嗨棒
    91 =>甜蜜舵手
    92 =>罪恶果园
    93 =>微醺薄荷
    94 =>墨西哥炸弹
    95 =>青绿心情
    96 =>经典嗨棒
    97 =>黄金咖啡
    98 =>粉红女郎
    99 =>酣甜如梦
    100 =>BeisiBeer
    101 =>血腥玛丽
    102 =>玛格丽特
    103 =>金汤力
    104 =>酒窖吸血鬼
    105 =>混合红酒
    106 =>天使莫吉托
    107 =>水果苏打
    108 =>清风茶园
}

map 酒杯{
    0=>一口杯
    1=>子弹杯
    2=>矮脚酒杯
    3=>古典杯
    4=>啤酒杯
    5=>锥底鸡尾酒杯
    6=>圆底鸡尾酒杯
    7=>圆盘鸡尾酒杯
    8=>红酒杯
    9=>水杯
    10=>咖啡杯
}

map 酒{
    20=>高贵的烈酒
    21=>浓烈的烈酒
    22=>香水般的烈酒
    23=>药草味的烈酒
    24=>甜润的烈酒
    25=>纯粹的烈酒
    26=>辛辣的烈酒
    27=>红酒
    28=>利口酒
    39=>啤酒
}
map 饮料{
    40=>碳酸饮料
    41=>苏打水
    42=>矿泉水
    43=>果汁
    44=>绿茶
    45=>奎宁水
    46=>甜牛奶
    47=>咖啡
}

map 调料{
    60=>薄荷叶
    61=>各式香草
    62=>辛香料
    63=>蜂蜜糖浆
    64=>番茄汁
    65=>柠檬
    66=>橄榄
    67=>盐巴
    68=>奶油
    69=>冰块
}
@enduml


