@startuml LiquorChart
skinparam Dpi 200
map 饮料口味{
    0=>甜
    1=>苦
    2=>淡
    3=>香
    4=>气泡
}
map 调料口味{
    0=>甜
    1=>酸
    2=>辣
    3=>咸
    4=>凉
    5=>香
}
map 容量{
    0=>小
    1=>中
    2=>大
}
map 度数{
    0=>低
    1=>中
    2=>高
}
@enduml


